version: "3.7"

volumes:
  bara.db.volume:

services:
  bara.app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - bara.db
    environment:
      DB_HOST: postgresql 
  bara.db:
    image: postgres:11.5-alpine
    container_name: bara.db
    ports:
      - 5432:5432
    volumes:
      - bara.db.volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
  bara.db-test:
    image: postgres:11.5-alpine
    container_name: bara.db-test
    ports:
      - 5555:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bara
    restart: always
  bara.redis:
    image: "redis:latest"
    ports:
      - 6379:6379
    volumes:
      - "./data/reis:/data"
