version: "3.7"

volumes:
  bara.db:

services:
  postgresql:
    image: postgres:11.5-alpine
    container_name: postgresql
    ports:
      - 5432:5432
    volumes:
      - bara.db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
