// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package bara

type CodeResult struct {
	Result string `json:"result"`
	Stdout string `json:"stdout"`
}

type Question struct {
	Slug        string `json:"slug"`
	Title       string `json:"title"`
	Description string `json:"description"`
}

type SubmitCode struct {
	TypedCode string `json:"typedCode"`
	Lang      string `json:"lang"`
	Slug      string `json:"slug"`
}
