// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package main

type SubmitCode struct {
	TypedCode string `json:"typedCode"`
	Lang      string `json:"lang"`
	Slug      string `json:"slug"`
	Result    string `json:"result"`
}
